services:
  frontend:
    image: httpd:latest
    ports:
      - 300:8080
    networks:
      - frontend
    configs:
      - httpd-config

  backend:
    image: python:3.9
    volumes:
      - db-data:/app/data
    networks:
      - backend

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tecvinson_registration
    ports:
      - 400:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:
    

configs:
  httpd-config:
    external: false

secrets:
  server-certificate:
    external: true

networks:
  # The presence of these objects is sufficient to define them
  frontend:
    # Specify driver options
    driver: bridge
  backend:
    # Specify driver options
    driver: bridge